# Generated by Django 5.2.5 on 2025-08-18 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_producto', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('stock_actual', models.IntegerField()),
                ('unidad_medida', models.CharField(max_length=50)),
                ('adquisicion', models.CharField(max_length=50)),
                ('precio_unitario', models.FloatField()),
                ('peso_unitario', models.FloatField()),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='NotaPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('orden_de_compra', models.CharField(max_length=100)),
                ('productos', models.JSONField()),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.cliente')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.proveedor')),
            ],
        ),
    ]
