# Generated by Django 5.2.5 on 2025-08-18 06:32

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notapedido',
            name='orden_de_compra',
        ),
        migrations.RemoveField(
            model_name='notapedido',
            name='productos',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='codigo_producto',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='peso_unitario',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='precio_unitario',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='stock_actual',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='unidad_medida',
        ),
        migrations.AddField(
            model_name='notapedido',
            name='orden_compra',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='codigo',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='peso',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='producto',
            name='unidad',
            field=models.CharField(default='unidad', max_length=50),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='notapedido',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='notapedido',
            name='tipo',
            field=models.CharField(choices=[('Entrada', 'Entrada'), ('Salida', 'Salida')], max_length=10),
        ),
        migrations.AlterField(
            model_name='producto',
            name='adquisicion',
            field=models.CharField(choices=[('Fabricacion', 'Fabricación'), ('Compra', 'Compra')], default='Compra', max_length=20),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='producto',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='gestion.proveedor'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nombre',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.CreateModel(
            name='NotaPedidoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('nota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='gestion.notapedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.producto')),
            ],
        ),
    ]
