# Generated by Django 5.2.5 on 2025-09-03 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_remove_notapedido_orden_de_compra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='unidad',
            field=models.CharField(choices=[('Und', 'Unidad'), ('Caja', 'Caja'), ('Paquete', 'Paquete'), ('Par', 'Par'), ('Docena', 'Docena'), ('Kg', 'Kilogramo'), ('g', 'Gramo'), ('Ton', 'Tonelada'), ('L', 'Litro'), ('mL', 'Mililitro'), ('Gal', 'Galón'), ('m', 'Metro'), ('cm', 'Centímetro'), ('mm', 'Milímetro'), ('Rollo', 'Rollo'), ('Pliego', 'Pliego'), ('Set', 'Set'), ('Kit', 'Kit')], default='Und', max_length=20),
        ),
    ]
