# Generated by Django 5.2.5 on 2025-10-10 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_alter_producto_unidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
    ]
